kind: pipeline
name: master-docker-build

clone:
  depth: 10

steps:
- name: notify the start on building work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK=${DRONE_BUILD_LINK}
  - export MSG_TITLE="⌛🗳 Start to build docker image for new master \`$DRONE_SOURCE_BRANCH\`(\`${DRONE_BUILD_NUMBER}\`)"
  - export MSG_CONTENT="click the link below to see the status"
  - ./shell/push-wechatwork.sh

- name: build and push docker images
  image: gnes/dind
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  environment:
    TCLOUD_USER:
      from_secret: TCLOUD_USER
    TCLOUD_PWD:
      from_secret: TCLOUD_PWD
    HUB_USER:
      from_secret: HUB_USER
    HUB_PWD:
      from_secret: HUB_PWD
    BADGE_WEBHOOK:
      from_secret: BADGE_WEBHOOK
    BOT_URL:
      from_secret: BOT_URL
    GITHUB_USER:
      from_secret: GITHUB_USER
    GITHUB_PWD:
      from_secret: GITHUB_PWD
  commands:
  - ./docker-build.sh
  - docker system prune -a -f

- name: notify the sucess on building work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK=$DRONE_REPO_LINK
  - export MSG_TITLE="✅🎁 All images are successfully delivered!"
  - export MSG_CONTENT=""
  - ./shell/push-wechatwork.sh

- name: notify the start on benchmark work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK=${DRONE_BUILD_LINK}
  - export MSG_TITLE="🏎️🐎 Start to benchmark the new master \`$DRONE_SOURCE_BRANCH\`(\`${DRONE_BUILD_NUMBER}\`)"
  - export MSG_CONTENT="click the link below to see the status"
  - ./shell/push-wechatwork.sh

- name: build and benchmarking
  image: gnes/dind
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: cache
    path: /workspace
  environment:
    TCLOUD_USER:
      from_secret: TCLOUD_USER
    TCLOUD_PWD:
      from_secret: TCLOUD_PWD
    HUB_USER:
      from_secret: HUB_USER
    HUB_PWD:
      from_secret: HUB_PWD
    BADGE_WEBHOOK:
      from_secret: BADGE_WEBHOOK
    BOT_URL:
      from_secret: BOT_URL
    GITHUB_USER:
      from_secret: GITHUB_USER
    GITHUB_PWD:
      from_secret: GITHUB_PWD
    DO_BENCHMARK:
      from_secret: DO_BENCHMARK
    BENCHMARK_DIR: /workspace/benchmark/
    SHARED_HOST_PATH: /tmp/
  commands:
  - ./benchmark-eval.sh
  - docker system prune -a -f

- name: notify the sucess on benchmark work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK="https://github.com/gnes-ai/benchmark"
  - export MSG_TITLE="✅🏍️ New benchmark is updated!"
  - export MSG_CONTENT=""
  - ./shell/push-wechatwork.sh

- name: notify the failure on all work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK=$DRONE_BUILD_LINK
  - export MSG_TITLE="❌🎁🏍️ fail to build and benchmark the docker image!"
  - export MSG_CONTENT="please inform [$DRONE_COMMIT_AUTHOR]($DRONE_COMMIT_AUTHOR_EMAIL) to modify and fix [\`$DRONE_SOURCE_BRANCH\`]($DRONE_COMMIT_LINK). click the link below to see the details."
  - ./shell/push-wechatwork.sh
  when:
    status:
    - failure

trigger:
  branch:
  - master
  event:
  - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: cache
  host:
    path: /tmp/

---

kind: pipeline
name: release-docker-build

clone:
  depth: 50

steps:
- name: notify the start on build work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK=$DRONE_BUILD_LINK
  - export MSG_TITLE="⌛🗳 Start to build docker image for new release \`$DRONE_SOURCE_BRANCH\`(\`${DRONE_TAG}\`)"
  - export MSG_CONTENT="[tag link](https://github.com/gnes-ai/gnes/tree/${DRONE_TAG}), click the link below to see the status"
  - ./shell/push-wechatwork.sh

- name: build and push docker images
  image: gnes/dind
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  environment:
    TCLOUD_USER:
      from_secret: TCLOUD_USER
    TCLOUD_PWD:
      from_secret: TCLOUD_PWD
    HUB_USER:
      from_secret: HUB_USER
    HUB_PWD:
      from_secret: HUB_PWD
    BADGE_WEBHOOK:
      from_secret: BADGE_WEBHOOK
    BOT_URL:
      from_secret: BOT_URL
    GITHUB_USER:
      from_secret: GITHUB_USER
    GITHUB_PWD:
      from_secret: GITHUB_PWD
  commands:
  - ./docker-build.sh

- name: notify the sucess on wechat work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK="https://github.com/gnes-ai/gnes/tree/${DRONE_TAG}"
  - export MSG_TITLE="✅🎁 All images are successfully delivered!"
  - export MSG_CONTENT=""
  - ./shell/push-wechatwork.sh

- name: notify the start on benchmark work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK=${DRONE_BUILD_LINK}
  - export MSG_TITLE="🏎️🐎 Start to benchmark the new master \`$DRONE_SOURCE_BRANCH\`(\`${DRONE_TAG}\`)"
  - export MSG_CONTENT="click the link below to see the status"
  - ./shell/push-wechatwork.sh

- name: build and benchmarking
  image: gnes/dind
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: cache
    path: /workspace
  environment:
    TCLOUD_USER:
      from_secret: TCLOUD_USER
    TCLOUD_PWD:
      from_secret: TCLOUD_PWD
    HUB_USER:
      from_secret: HUB_USER
    HUB_PWD:
      from_secret: HUB_PWD
    BADGE_WEBHOOK:
      from_secret: BADGE_WEBHOOK
    BOT_URL:
      from_secret: BOT_URL
    GITHUB_USER:
      from_secret: GITHUB_USER
    GITHUB_PWD:
      from_secret: GITHUB_PWD
    DO_BENCHMARK:
      from_secret: DO_BENCHMARK
    BENCHMARK_DIR: /workspace/benchmark/
    SHARED_HOST_PATH: /tmp/
  commands:
  - ./benchmark-eval.sh
  - docker system prune -a -f

- name: notify the sucess on benchmark work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK="https://github.com/gnes-ai/benchmark"
  - export MSG_TITLE="✅🏍️ New benchmark is updated!"
  - export MSG_CONTENT=""
  - ./shell/push-wechatwork.sh

- name: notify the failure on all work
  image: byrnedo/alpine-curl
  environment:
    BOT_URL:
      from_secret: BOT_URL
  commands:
  - export MSG_LINK=$DRONE_BUILD_LINK
  - export MSG_TITLE="❌🎁🏍️ fail to build and benchmark the docker image!"
  - export MSG_CONTENT="[tag link](https://github.com/gnes-ai/gnes/tree/${DRONE_TAG}) please inform [$DRONE_COMMIT_AUTHOR]($DRONE_COMMIT_AUTHOR_EMAIL) to modify and fix [\`$DRONE_SOURCE_BRANCH\`]($DRONE_COMMIT_LINK). click the link below to see the details."
  - ./shell/push-wechatwork.sh
  when:
    status:
    - failure

trigger:
  event:
  - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: cache
  host:
    path: /tmp/