!PipelineEncoder
components:
  - !Word2VecEncoder
    parameters:
      model_dir: /ext_data/sgns.wiki.bigram-char.refine
    gnes_config:
      is_trained: true
  - !PCALocalEncoder
    parameters:
      output_dim: 200
      num_locals: 10
    gnes_config:
      batch_size: 2048
  - !PQEncoder
    parameters:
      cluster_per_byte: 20
      num_bytes: 10
